### ISSUE TITLE
Docker file fails

### ISSUE THREAD

**Issue by ehwest** [vk-twiconnect/sfx-creator-service#10]
Executing busybox-1.26.2-r11.trigger
OK: 5 MiB in 15 packages
 ---> eba061c7067f
Removing intermediate container 3ca10fe7f5f6
Step 6/11 : WORKDIR /usr/src/app
 ---> 85ce70cf6e21
Removing intermediate container b5eb24072fae
Step 7/11 : COPY package*.json ./
 ---> 072ec13c7fe9
Removing intermediate container 7569809f07b2
Step 8/11 : RUN npm install
 ---> Running in 7cacf4e43a6c
npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
npm ERR! request to https://registry.npmjs.org/bytes/-/bytes-3.0.0.tgz failed, reason: connect ENETUNREACH 2400:cb00:2048:1::6810:1123:443 - Local (:::0)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-18T18_57_26_209Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1

**Comment by vkhazin** [comment]
Updated Dockerfile to re-use node:alpine image
