### ISSUE TITLE
long curl seems to break.

### ISSUE THREAD

**Issue by ehwest** [vk-twiconnect/sfx-creator-service#12]
The basics seem to work for trivially small files provided.
However, I used a set of real files to be packed into the EXE and got
this message:
./curl_content_test
./curl_content_test: line 1: /usr/bin/curl: Argument list too long

Please see the file curl_content_test  (attached)
[curl_content_test.txt](https://github.com/vk-twiconnect/sfx-creator-service/files/2304068/curl_content_test.txt)

**Comment by ehwest** [comment]
My copy of the web service is here:   http://74.88.134.103:3000/

**Comment by vkhazin** [comment]
Testing using Postman to figure out whether it is a curl problem or the service problem.

**Comment by vkhazin** [comment]
Increased limit for request body to .5gb.
Rebuild and redeployed to heroku to validate.
Please advise in case there are still troubles.

**Comment by vkhazin** [comment]
Please note the sample data was an invalid json with missing comma between files e.g. `..} no-comma-here {...`.
Corrected json is ./test/sampleData.json
