### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by ehwest** [vk-twiconnect/sfx-creator-service#13]
Steps to create:
docker build . --tag twiconnect/sfx-creator-service:1.0 &&   docker run -it -d -p 3000:3000 --rm --name sfx-creator-service twiconnect/sfx-creator-service:1.0
docker run -it -d -p 3000:3000 --rm --name sfx-creator-service twiconnect/sfx-creator-service:1.0 

Used test harness to build curl_test.sh (attached) and then executed it (fixed missing commas).

Error message:
./curl_test.sh: line 1: /usr/bin/curl: Argument list too long
[curl_test4.txt](https://github.com/vk-twiconnect/sfx-creator-service/files/2308507/curl_test4.txt)

I'm thinking that passing the files to a curl isnt going to work.

Maybe we should just point to the files using a URL instead of file contents in the request.  Presumably the URL would serve up files on the local file system, perhaps using a -v volume attached to the container, not sure.

**Comment by vkhazin** [comment]
If passing files in a post body won't work then returning sfx in the body also will be a trouble

Maybe we should revise the requirements:
1. s3 bucket to store the core components and the post request to pass configuration.xml only
2. the micro-service will process the files from s3 plus the configuration.xml from the post body
3. the micro-service will store the output on s3 bucket
4. the micro-service will return the url to the generated file

What you think?

**Comment by vkhazin** [comment]
I have tested against my heroku deployment and it seemed to work:
 curl -XP-98d0-529269fb1459"               -d  "@./test/sampleData.json" 'https://sfx-creator-service-dev.herokuapp.com/zip'

Where "./test/sampleData.json" is a copy of curl_test4.txt file

**Comment by ehwest** [comment]
The length of the returned json has not emerged as a problem.

The above heroku test has the very large input data files in a file system.
So It looks like we have to use a file system to get the files into the microservice.
The _return_ of a large file (with a .zip or .exe) suffix works fine.
So our json-bearing API call to the microservice needs to provide the URLs with optional S3 credentials --instead of the actual file contents.

**Comment by vkhazin** [comment]
Let's connect when you can, seems like we are getting different experiences with the same code and the payload.

**Comment by ehwest** [comment]
I need to test the local filename input tonight and will figure this out
after that.
My guess is it will work just fine.
Earle

**Comment by ehwest** [comment]
Works fine:
curl -XPOST   -H "Content-Type: application/json"  \
-H "x-api-key: f84e2396-9c14-11e8-98d0-529269fb1459" \
-d  "@./test/sampleData.json" 'https://sfx-creator-service-dev.herokuapp.com/zip'
